@WebApi_HostAddress = https://localhost:7258

### Get Liveness
GET {{WebApi_HostAddress}}/alive
Accept: text/plain

### Get Health
GET {{WebApi_HostAddress}}/health
Accept: text/plain

### Get OpenAPI Document
GET {{WebApi_HostAddress}}/openapi/v1.json

### Get All Referrals from XY7G4D
GET {{WebApi_HostAddress}}/referrals?code=XY7G4D
Accept: application/json

### Create Referral
POST {{WebApi_HostAddress}}/referrals
Accept: application/json
Content-Type: application/json

{
  "code": "ABC123",
  "referee": {
    "firstName": "Alex",
    "lastName": "Miller"
  }
}

### Get New Referral
GET {{WebApi_HostAddress}}/referrals?code=ABC123
Accept: application/json

### Get Pending Referrals
GET {{WebApi_HostAddress}}/referrals?code=XY7G4D&status=Pending
Accept: application/json

### Complete Helen Referral
PATCH {{WebApi_HostAddress}}/referrals/019484a6-2d26-773a-a3cd-f73f90f25448/status
Accept: application/json
Content-Type: application/json

"Complete"

### Get Helen Referral By ID
GET {{WebApi_HostAddress}}/referrals/019484a6-2d26-773a-a3cd-f73f90f25448
Accept: application/json

###