name: .NET Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x

    - name: Validate formatting
      run: dotnet format --verify-no-changes --verbosity normal

    - name: Restore dependencies
      run: dotnet restore --verbosity normal

    - name: Build
      run: dotnet build --no-restore --verbosity normal

    - name: Test
      run: dotnet test --no-build --verbosity normal
